fos_user:
  db_driver: orm
  firewall_name: login
  user_class: App\Entity\User
  from_email:
    address: "%from_email%"
    sender_name: "%sender_name%"
  registration:
    confirmation:
      enabled: false
      template: FOSUserBundle:Registration:email.txt.twig
      from_email:
        address: "%from_email%"
        sender_name: "%sender_name%"
  service:
    mailer: fos_user.mailer.twig_swift
  resetting:
    email:
      template: FOSUserBundle:Resetting:email.txt.twig