security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        token_provider:
            id: App\Security\TokenProvider

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/token, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/league, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }

    firewalls:
        register:
            pattern: ^/register
            anonymous: true
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
        secured:
            pattern: ^/
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - App\Security\JWTGuardAuthenticator
            provider: token_provider