App\Model\Request\TeamInput:
    properties:
        name:
          - NotBlank:
              message: "The name is required"
        strip:
          - NotBlank:
              message: "The strip is required"