# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    from_email: '%env(EMAIL_FROM)%'
    sender_name: '%env(EMAIL_SENDER_NAME)%'
    token_life: 86400
    token_algorithm: 'HS256'
    cache_time_tolerance: 300
    redis_host: '%env(REDIS_HOST)%'
    secret: '%env(SECRET)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\ParamConverters\InputModelParamConverter:
        arguments: ['@serializer', '@validator']
        tags:
            - { name: request.param_converter }

    App\EventListener\EntityValidationExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception}

    App\Repository\UserRepository:
        arguments: ['@doctrine']

    app.library.jwt:
        class: Firebase\JWT\JWT

    App\Util\TokenUtil:
        arguments:
            $jwt: '@app.library.jwt'
            $cache: '@snc_redis.token'
            $tokenLife: '%token_life%'
            $algorithm: '%token_algorithm%'
            $cacheTime: '%cache_time_tolerance%'
            $secret: '%secret%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones